[package]
name = "update"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.81"
httparse = "1.7.1"
sha2 = "0.10.2"
hmac = "0.12.1"
hex = "0.4"
dotenv = "0.15.0"